### ISSUE TITLE
Is there any way to get the matching point list?

### ISSUE THREAD

**Issue by ZHANGKEON** [chulminy/Autonomous_Image_Localization#2]

**Comment by chulminy** [comment]
What do you mean "matching point list"? 
Can you explain it in detail and its purpose? 

Chul min

**Comment by ZHANGKEON** [comment]
I  planned to do further point cloud processing in Matlab and for such purpose I want to get the 3D coordinates of feature point. Now the problem is solved. Thanks for your quick reply.

**Comment by chulminy** [comment]
Great !!

**Comment by ZHANGKEON** [comment]
I still has a question about the code:

In the DemoCoordTrans, you mention that "you are going to pick a point on UNDISTORTED IMAGES!".  That means "u = zeros(2,nTest)" is the pixel coordinate in undistorted images.  Then, in the DemoOutput, you use "X  = _X_from_xP_nonlin(u,P,imSize);" to get the corresponding 3D coordinate in SfM system, where the P is the projection matrix already including the image distortion from VisualSFM. Why not apply this P  on the Original image?

Thanks.

Chaobo

**Comment by chulminy** [comment]
P does not contain image distortion (lens distortion) parameters. In the SfM process, a lens distortion parameter (a single in VisualSfM) of each image is calibrated. Projective relationship (x = PX) is only valid between undistorted images and world points in 3D. That's why we need to undistort images first to use P.

Here, http://ccwu.me/vsfm/doc.html
You can check that the camera model used in VisualSfM tune one radial distortion parameter.

If it is not clear, please let me know.

Chul Min

**Comment by ZHANGKEON** [comment]
Dear Chul Min,

Well noted. I just check the P and K and both of them don't consider the lens distortion. Thanks again.

Chaobo

**Comment by ZHANGKEON** [comment]
Actually, I am wondering is there anyway to get the homography matrix between two images? Just use the camera parameters (e.g. K, P and rDIst) from VisualSFM without doing ransacfithomography. Thanks.

**Comment by chulminy** [comment]
Yes. P does not contain distortion parameters.

The homography matrix is a 3 x 3 matrix providing **planar** projective transformation between two images. In other words, two images should look at the same plane. If they include two different planes (different position s in 3D), two homograph matrices are found from these images. There is a way to find a homography from P but you need to first specify a plane between them.

**Comment by ZHANGKEON** [comment]
Does that mean I can not get an accurate homography matrix between two images (the two images just has a certain amount of the same scene)? When I try to apply ransacfithomography to the matched SIFT feature points from two images, the accuracy is low. So I am wonder is there anyway to get the  homography matrix from the parameters obtained from VisualSFM, directly.

**Comment by chulminy** [comment]
I'm not talking about its accuracy. If your scene contains more than one planes (e.g. 3D geometry) and your images don't have the same optical center (e.g. panorama image), you can't find a single homography between two images. I don't think your images are captured with only angle variations. 
See this: 
https://stackoverflow.com/questions/17615500/2d-3d-homography-matrix-estimation

It is a topic that people are commonly confused.

See this
https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#findhomography

It clearly says that srcPoints and dstPoints are points in the **plane**.

**Comment by ZHANGKEON** [comment]
My image is not taken by a rotating camera such that the images don't have the same optical cente.  Actually, I am using the the pixel coordinate of the matching points on two images to find the homography between these two images. To find H matrix, four corresponding points is enough. However, when I apply the matched more feature points from VisualSFM (F matrix) to get H matrix, the accuracy is low.  I use the matching points in 2D image plane so I think they satisfy the reqiirement "srcPoints and dstPoints are points in the plane".

**Comment by ZHANGKEON** [comment]
I think I make some mistakes. When the real object is  a plane,  the homography between these two images has a high accuracy when appled to the image points on this plane. So I think the homography can only be apply to the planer object or using a rotating camera. I will try to understand it with more details. Thanks.

**Comment by chulminy** [comment]
Exactly. If possible, you can share your sample images here so that I can give more constructive comments.

**Comment by ZHANGKEON** [comment]
Sure. I am currently doing some tentative work and find your code is very useful. What I want to do is like this, if I select the end point of a black line on concrete cube in the first image, then the code will automatically find the matching point on second image through homography, and thus I can use triangulation to compute the 3D  world coordinate of it. I have already know the camera matrix and  other camera parameters  from VisualSFM and also the Transformation matrix M. 

According to what we have discussed, I need to compute multiple homography matrix for each planer object or using a rotating camera to take the images. However, I found that computing multiple homography matrix requires detecting the planer object firstly, and this coding part for plane extraction is not easy for me. Thanks.

Attached are two undistorted images.

![img_5983](https://user-images.githubusercontent.com/17973864/36010125-c49647b8-0d8a-11e8-86dc-c980562d3254.JPG)
![img_5982](https://user-images.githubusercontent.com/17973864/36010126-c4c085dc-0d8a-11e8-845f-9c8121c69f79.JPG)

**Comment by chulminy** [comment]
I think you are working on automated crack quantification for concrete structures. 
As mentioned before, you can't find the corresponding point on the second images automatically. You can only know a corresponding line (called, a epipolar line) that passes through the corresponding point.

There is some text to explain this in my previous paper:
http://onlinelibrary.wiley.com/doi/10.1111/mice.12141/abstract
https://github.com/chulminy/Vision_Based_Automated_Crack

In your research, finding a homography matrix is not useful unless you take only one plane. 

Fortunately, crack (black line) on concrete seem to be visually prominent, which means that it is likely to generate a couple of features (e.g. sift or surf) at tips of the black line and they create 3D points in your SfM process by matching them. You know the correspondence of these features so you don't need a homography matrix.

Thus, my suggestion is, rather than selecting random points in image 1, you select a feature near the tip of the black line. 

Plotting features on images is a good starting point to do this.

**Comment by ZHANGKEON** [comment]
You are right. The feature points will be generated at tips and around the contour of black line. Thanks for your very good suggestion.

**Comment by chulminy** [comment]
Great !!
